import { createClient } from '@supabase/supabase-js';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import CardPreview from '@/components/card/CardPreview';
import { CardTheme } from '@/components/card/themes'; // ✅ اصلاح شده

export const dynamic = 'force-dynamic';

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

interface PageProps {
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ theme?: string }>;
}

export async function generateMetadata({ params }: PageProps) {
  try {
    const { slug } = await params;
    const { data: snippet } = await supabaseAdmin
      .from('snippets')
      .select('card_title, username')
      .eq('slug', slug)
      .single();

    if (!snippet) {
      return { title: 'Card Not Found' };
    }

    return {
      title: `${snippet.card_title || 'Code Card'} | Zbloue Card`,
      description: 'View this beautiful code card generated by Zbloue',
    };
  } catch {
    return { title: 'Card | Zbloue' };
  }
}

export default async function CardPage({ params, searchParams }: PageProps) {
  try {
    const { slug } = await params;
    const { theme = 'blue' } = await searchParams;

    const { data: snippet, error } = await supabaseAdmin
      .from('snippets')
      .select('*')
      .eq('slug', slug)
      .single();

    if (error || !snippet) {
      console.error('❌ Snippet not found:', error);
      notFound();
    }

    const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://Zbloue.vercel.app';

    const validThemes: CardTheme[] = [
      'dark', 'blue', 'purple', 'pink', 'gradient',
      'orange', 'gold', 'green', 'lavender', 'silver',
      'glass', 'light', 'white'
    ];
    const selectedTheme = validThemes.includes(theme as CardTheme) ? (theme as CardTheme) : 'blue';

    return (
      <main className="min-h-screen bg-[#0f0f14] flex flex-col items-center justify-center p-4 md:p-8">
        <div className="max-w-4xl w-full">
          
          <div className="flex justify-between items-center mb-6">
            <Link 
              href={`/snippet/${slug}`} 
              className="text-[#89b4fa] hover:text-[#b4befe] transition-colors inline-flex items-center gap-2 text-sm font-medium"
            >
              ← Back to Analysis
            </Link>
          </div>

          <div className="flex justify-center overflow-hidden rounded-xl shadow-2xl scale-75 md:scale-100">
            <CardPreview
              title={snippet.card_title || 'Code Analysis'}
              summary={snippet.key_concept || 'Analysis of the provided code snippet.'}
              username={snippet.username || 'Developer'}
              slug={snippet.slug}
              language={snippet.language || 'javascript'}
              showCode={true}
              codeSnippet={snippet.raw_code || ''}
              createdAt={snippet.created_at}
              githubUsername={snippet.github_username || undefined}
              theme={selectedTheme}
              interactive={true}
            />
          </div>

          <div className="mt-6 text-center text-xs text-[#6c7086]">
            <p>
              Generated by{' '}
              <a
                href={appUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#89b4fa] hover:text-[#b4befe] transition-colors"
              >
                Zbloue
              </a>
              {' '}· AI Code Analysis
            </p>
          </div>
        </div>
      </main>
    );
  } catch (error) {
    console.error('❌ Error loading card page:', error);
    notFound();
  }
}